In [16]:
import pandas as pd
import os
import datetime
import time

In [17]:
b = pd.read_excel('Time-4-20/2019-04-20-12-32-39.xlsx')
b

          Start          End Answers Hand
0           NaN  00:00:07:50     NaN  NaN
1   00:00:11:50  00:00:26:39       0  NaN
2           NaN  00:00:57:10     NaN  NaN
3   00:00:59:50  00:01:10:39       1  NaN
4           NaN  00:01:28:32     NaN  NaN
5           NaN  00:01:31:08     NaN  NaN
6           NaN  00:01:40:51     NaN  NaN
7           NaN  00:01:44:13     NaN  NaN
8           NaN  00:02:42:35      no    L
9           NaN  00:02:44:22      no  NaN
10          NaN  00:02:46:09      no  NaN
11          NaN  00:03:02:32      no    L
12          NaN  00:03:04:41     yes  NaN
13          NaN  00:03:06:31     yes  NaN
14          NaN  00:03:24:59     yes    L
15          NaN  00:03:27:00     yes  NaN
16          NaN  00:03:28:37     yes  NaN

In [18]:
a = pd.read_excel('2/2019-04-20-14-59-58.xlsx')
a

       Start       End Answers Hand
0   00:03:41       NaN     NaN  NaN
1   00:10:30  00:28:30       0  NaN
2   00:37:55       NaN     NaN  NaN
3   00:45:10  01:01:20       1  NaN
4   01:21:07       NaN     NaN  NaN
5   01:24:58       NaN     NaN  NaN
6   01:33:59       NaN     NaN  NaN
7   01:38:05       NaN     NaN  NaN
8   03:18:14       NaN      no    R
9   03:20:42       NaN      no  NaN
10  03:23:26       NaN      no  NaN
11  03:48:27       NaN      no    R
12  03:51:11       NaN      no  NaN
13  03:53:39       NaN     yes  NaN
14  04:16:54       NaN     yes    L
15  04:19:13       NaN     yes  NaN
16  04:21:44       NaN     yes  NaN

In [19]:
def cvtime(time):
    a = time.split(':')[1]
    b = int(time.split(':')[-1].split('.')[0])
    c = time.split(':')[-1].split('.')[-1]
    c = int(float('0.'+c)*60)
    newt = '00:%s:%02d:%02d'%(a,b,c)
    return newt

def contime2(time):
    tsplit = time.split(':')
    sec = sum(float(t)*i for i,t in zip([60,1,1./60],tsplit))
    return sec+1.2
# sec = contime2('00:03:41')
# addt = str(datetime.timedelta(seconds=sec))

# cvtime(addt)

'00:00:04:52'

In [20]:
import math
xpath = '2/'
for xname in os.listdir(xpath):
    a = pd.read_excel(xpath+xname)
    if math.isnan(a['End'][0]):
        for i in range(17):
            if i ==1 or i ==3:
                a['Start'][i]='00:'+str(a['Start'][i])
                a['End'][i]='00:'+str(a['End'][i])
            temt = str(a['Start'][i])
            sec  = contime2(temt)
            addt = str(datetime.timedelta(seconds=sec))
            temt = cvtime(addt)
            a['Start'][i] = None
            a['End'][i] = temt
        a.to_excel(xname,index=False)

ModuleNotFoundError: No module named 'openpyxl'

In [9]:
import pandas as pd
import os
import datetime
import math
import time

def cvtime(time):
    a = time.split(':')[1]
    b = int(time.split(':')[-1].split('.')[0])
    c = time.split(':')[-1].split('.')[-1]
    c = int(float('0.'+c)*60)
    newt = '00:%s:%02d:%02d'%(a,b,c)
    return newt

def cvtime1(time):
    a = time.split(':')[0]
    b = int(time.split(':')[-1].split('.')[0])
    c = time.split(':')[-1].split('.')[-1]
    c = int(float('0.'+c)*60)
    newt = '00:%s:%02d:%02d'%(a,b,c)
    return newt

def toseconds(time):
    tlist = time.split(':')
    sec = sum(float(x)*i for x,i in zip(tlist,[60,1]))
    return sec+1.2

for item in os.listdir('Time-4-20'):
    print(item)
    nw_item = item.split('.')[0]+'_new'+'.xlsx'
    toconv = pd.read_excel('Time-4-20/'+item)
    print(toconv)
    check = toconv['Start'][0]
#     print(toconv)
    if isinstance(check,str):
        for i in range(17):
            if i ==1 or i ==3:
                toconv['Start'][i] = cvtime1(toconv['Start'][i])
                toconv['End'][i] = cvtime1(toconv['End'][i])
                continue
            temt = toconv['Start'][i]
            sec = toseconds(temt)
            addt = str(datetime.timedelta(seconds=sec))
            cvt = cvtime(addt)
            toconv['Start'][i] = None
            toconv['End'][i] = cvt
        toconv.to_excel(nw_item,index = False)

2019-04-20-13-59-03.xlsx
          Start          End Answers Hand
0           NaN  00:00:05:40     NaN  NaN
1   00:00:08:30  00:00:23:22       1  NaN
2           NaN  00:00:29:22     NaN  NaN
3   00:00:32:00  00:00:46:47       0  NaN
4           NaN  00:01:03:08     NaN  NaN
5           NaN  00:01:05:25     NaN  NaN
6           NaN  00:01:17:05     NaN  NaN
7           NaN  00:01:22:22     NaN  NaN
8           NaN  00:02:07:05      no    R
9           NaN  00:02:09:07      no  NaN
10          NaN  00:02:11:00      no  NaN
11          NaN  00:02:31:30      no    R
12          NaN  00:02:33:27     yes  NaN
13          NaN  00:02:35:28     yes  NaN
14          NaN  00:02:48:39      no    R
15          NaN  00:02:50:37   maybe  NaN
16          NaN  00:02:52:56     yes  NaN
2019-04-20-16-32-39.xlsx
      Start      End Answer Hand
0   00:06.2      NaN    NaN  NaN
1   00:10.9  00:29.5      1  NaN
2   00:35.0      NaN    NaN  NaN
3   00:40.0  00:55.2      0  NaN
4   01:12.0      NaN    NaN  NaN
5   01:14.7      NaN    NaN  NaN
6   01:33.0      NaN    NaN  NaN
7   01:36.0      NaN    NaN  NaN
8   02:26.2      NaN     no    R
9   02:28.0      NaN     no  NaN
10  02:30.1      NaN     no  NaN
11  02:55.8      NaN     no    R
12  02:57.7      NaN     no  NaN
13  02:59.6      NaN    yes  NaN
14  03:21.8      NaN    yes    L
15  03:23.4      NaN    yes  NaN
16  03:26.3      NaN    yes  NaN

ModuleNotFoundError: No module named 'openpyxl'

In [6]:
toconv =pd.read_excel('Time-4-20/2019-04-20-14-59-58.xlsx')
# a =pd.read_excel('Time-4-20/2019-04-20-16-49-33.xlsx')
nw_item= '2019-04-20-14-59-58.xlsx'
toconv.to_excel(nw_item,index = False)

ModuleNotFoundError: No module named 'openpyxl'

In [5]:
for item in os.listdir('6'):
    item

In [56]:
def cvtime(time):
    a = time.split(':')[1]
    b = int(time.split(':')[-1].split('.')[0])
    c = time.split(':')[-1].split('.')[-1]
    c = int(float('0.'+c)*60)
    newt = '00:%s:%02d:%02d'%(a,b,c)
    return newt

print(cvtime('0:01:33.800000'))

00:01:33:48

In [57]:

def toseconds(time):
    tlist = time.split(':')
    sec = sum(float(x)*i for x,i in zip(tlist,[60,1]))
    return sec+1.2
seconds=toseconds('01:32.6')
# print('{:d}:{:02d}:{:02d}'.format(h, m, s))
addt = str(datetime.timedelta(seconds=toseconds('01:32.6')))
# cvtime(addt)

print(addt)

0:01:33.800000

In [7]:
def cvtime(time):
    a = time.split(':')[1]
    b = int(time.split(':')[-1].split('.')[0])
    c = time.split(':')[-1].split('.')[-1]
    c = int(float('0.'+c)*60)
    newt = '00:%s:%02d:%02d'%(a,b,c)
    return newt

def toseconds(time):
    tlist = time.split(':')
    sec = sum(float(x)*i for x,i in zip(tlist,[60,1]))
    return sec+1.2

for item in os.listdir('6'):
    toconv = pd.read_excel('6/'+item)
    if toconv['Start'][0] is not None:
        for i in range(17):
            if i ==1 or i ==3:
                continue
            temt = toconv['Start'][i]
            sec = toseconds(temt)
            addt = str(datetime.timedelta(seconds=sec)
            print(addt)
            cvt = cvtime(addt)
            toconv['Start'][i] = None
            toconv['End'][i] = cvt

SyntaxError: invalid syntax (<ipython-input-7-808034f5bca1>, line 23)

In [31]:
toconv = pd.read_excel('6/'+item)
type(toconv['Start'][0])
# toconv['Start']=None
print(toconv)

      Start      End Answer Hand
0    00:5.5      NaN    NaN  NaN
1    00:9.1  00:26.9      0  NaN
2   00:35.4      NaN    NaN  NaN
3   00:39.4  00:53.4      1  NaN
4   01:14.5      NaN    NaN  NaN
5   01:17.2      NaN    NaN  NaN
6   01:29.0      NaN    NaN  NaN
7   01:32.6      NaN    NaN  NaN
8   02:22.4      NaN     no    L
9   02:24.2      NaN     no  NaN
10  02:26.0      NaN     no  NaN
11  02:48.5      NaN    yes    R
12  02:50.4      NaN    yes  NaN
13  02:52.3      NaN     no  NaN
14  03:12.6      NaN     no    R
15  03:14.5      NaN    yes  NaN
16  03:16.3      NaN    yes  NaN

In [4]:
xname = '2019-04-20-13-52-09.xlsx'
viname = xname.split('.')[0]+'.mp4' 
a = pd.read_excel(xname)

FileNotFoundError: [Errno 2] No such file or directory: '2019-04-20-13-52-09.xlsx'

In [11]:
a

          Start          End Answers Hand
0           NaN  00:00:08:00     NaN  NaN
1   00:00:11:21  00:00:25:26     NaN  NaN
2           NaN  00:00:34:39     NaN  NaN
3   00:00:37:45  00:00:56:14     NaN  NaN
4           NaN  00:01:15:17     NaN  NaN
5           NaN  00:01:18:40     NaN  NaN
6           NaN  00:01:31:09     NaN  NaN
7           NaN  00:01:34:30     NaN  NaN
8           NaN  00:02:11:53      no    L
9           NaN  00:02:14:00      no  NaN
10          NaN  00:02:15:51      no  NaN
11          NaN  00:02:35:53     yes    R
12          NaN  00:02:38:08     yes  NaN
13          NaN  00:02:40:05     yes  NaN
14          NaN  00:02:55:21      no    L
15          NaN  00:02:57:13      no  NaN
16          NaN  00:02:59:21      no  NaN

In [19]:
17

False

In [51]:
x = time.strptime('00:01:00:50','%H:%M:%S:%f')
# x = time.strptime('00:01:00,000'.split(',')[0],'%H:%M:%S')
datetime.timedelta(hours=x.tm_hour,minutes=x.tm_min,seconds=x.tm_sec).total_seconds()

60.0

In [52]:
def transtime(x):
    tlist =x.split(':')
    tsecon = sum(x * float(t) for x, t in zip([3600, 60, 1, 1./60], tlist)) 
    return tsecon

In [62]:
for i in range(17):
    tstop = transtime(a['End'][i])
    if not i ==1 or i ==3:
        tstar = tstop - 1
    else:
        tstar = transtime(a['Start'][i])
    print('start:%f'%tstar)
    print('stop:%f \n'%tstop)
    comm = '/usr/bin/ffmpeg -i {} -ss {} -to {} {}.mp4'.format(viname,tstar,tstop, i)
#     !!comm

start:7.000000
stop:8.000000

start:11.350000
stop:25.433333

start:33.650000
stop:34.650000

start:55.233333
stop:56.233333

start:74.283333
stop:75.283333

start:77.666667
stop:78.666667

start:90.150000
stop:91.150000

start:93.500000
stop:94.500000

start:130.883333
stop:131.883333

start:133.000000
stop:134.000000

start:134.850000
stop:135.850000

start:154.883333
stop:155.883333

start:157.133333
stop:158.133333

start:159.083333
stop:160.083333

start:174.350000
stop:175.350000

start:176.216667
stop:177.216667

start:178.350000
stop:179.350000

In [40]:
transtime(a['End'][0])

60.833333333333336

In [64]:
!!ls

['2019-04-20-13-52-09.xlsx',
 '2019-04-20-16-49-33',
 '2019-04-20-16-49-33.mp4',
 '2019-04-20-16-49-33.xlsx',
 'splitxls.py',
 'tryitout.ipynb']